### ISSUE TITLE
Do "created" as well?

### ISSUE THREAD

**Issue by toddz262** [alangrainger/obsidian-frontmatter-modified-date#12]
I really appreciate having a reliable field for date modified that's separate from the file system - thank you.

Given that file systems can't maintain date created across various operating systems and syncs, I would LOVE to see an internal "created" field included here as well.

**Comment by alangrainger** [comment]
This is added in 1.4.2 - sorry it took so long!

**Comment by toddz262** [comment]
Wonderful -- thanks so much!
