### ISSUE TITLE
"Merging Changes" Popup with Sync

### ISSUE THREAD

**Issue by michaelzemba** [alangrainger/obsidian-frontmatter-modified-date#13]
I'm getting the "Merging Changes" pop-up frequently when using Obsidian Sync, and rather than being just an annoyance, it is actually erasing recent changes (e.g., I'll type out a sentence and then see half of it disappear when the sync conflict occurs).

Steps to reproduce: Obsidian running on a desktop (Windows 11) and mobile (Android 13) with Obsidian Sync. Edit a note on desktop. Stop making changes, but leave it in edit mode. Switch to mobile. Open the same note and start typing -- frequent "Merging Changes" pop-ups occur and text is often erased shortly after it is typed. 

After some experimentation, I think this is because I had sync turned on for "Installed Community Plugins" and "Active Community Plugin List". Thus, this plugin was installed and enabled on both desktop and mobile, which is probably not an optimal setup...? I suspect the edits were being synced appropriately, but then the mobile and desktop instances of the plugin were racing to update the modified date.

If that is what's going on, I guess it's not really a bug, but I would suggest emphasizing in the documentation somewhere to NOT enable the plugin on multiple devices, as it was a bit of a headache for awhile.

**Comment by michaelzemba** [comment]
Did a little more testing, enabling the plugin on only one device at a time and editing on others. The issue does still happen with the plugin enabled on only one device, but it only happens when it's the inactive device has the plugin enabled.

Plugin OFF on desktop + ON on mobile: editing on mobile is OK, but editing on PC causes sync issues
Plugin ON on desktop + OFF on mobile: editing on PC is OK, but editing on mobile causes sync issues

So it seems like the problem is having the plugin enabled on a device you are not using, while editing a note that is also open on that device.

**Comment by alangrainger** [comment]
Is this still an issue? The race condition with multiple syncing Obsidian instance has been accounted for in the code now, so hopefully this is no longer happening.
