### ISSUE TITLE
Global "append_modified_update" toggle?

### ISSUE THREAD

**Issue by lwshaban** [alangrainger/obsidian-frontmatter-modified-date#14]
Hello @alangrainger, this plugin is exactly what I was looking for, thank you for making it! One thing though, I intend to always append the modified dates into a list in the front matter for all my files and therefore do not particularly want to have to add the "append_modified_update" checkbox to each of my files. Is it possible to get a global setting to enable this, which could be added as an OR argument into the if statement? Thanks for your time, Lawrence.

**Comment by alangrainger** [comment]
Added in 1.4.0
