### ISSUE TITLE
When the plugin updates the modified date it removes the enclosing " " from an image URL in the image property 

### ISSUE THREAD

**Issue by ykr973** [alangrainger/obsidian-frontmatter-modified-date#17]
For some reason when obsidian-frontmatter-modified-date plugin updates the modified date of a note it removes the " " enclosing a URL in the image property. For Obsidian Publish users this breaks the image property which is required to specify a social media preview image.

The other popular plugin that does this (https://github.com/beaussan/update-time-on-edit-obsidian) has the exact same issue but for some reason the linter plugin does not.

https://github.com/alangrainger/obsidian-frontmatter-modified-date/assets/119615486/e42d6deb-4dc7-4997-963f-9980b8614bf9

**Comment by alangrainger** [comment]
This isn't anything to do with the plugin sorry - that's just what Obsidian does when it processes your frontmatter.

Here's the most recent post on the forum with someone complaining about this just today:

https://forum.obsidian.md/t/removing-final-element-in-yaml-array-inconsistent-behaviour/86653/6
