### ISSUE TITLE
Feature request: UTC time

### ISSUE THREAD

**Issue by ykr973** [alangrainger/obsidian-frontmatter-modified-date#18]
I would be nice to have the option to specify UTC.

**Comment by alangrainger** [comment]
Can you give some details as to where UTC would be necessary where ISO8601 formatted date and time with timezone won't be acceptable?

**Comment by ykr973** [comment]
That would work if it accomplishes the same thing thing but not sure how to do with that your plugin?  What would formatting would I specify to get the equivalent UTC as the output?

**Comment by alangrainger** [comment]
The default formatting is exactly that, so just leave the field blank. It's ISO8601 formatted date and time with timezone (or ATOM format).

Looks like this, and is parsable by almost any datetime software/library:

```
2024-01-20T11:54:52+00:00
```

**Comment by ykr973** [comment]
If I want to format it as 2024-01-20 13:54:52 or 2024-01-20 13:54 is that possible while retaining the UTC time zone?

**Comment by alangrainger** [comment]
My recommendation would be to keep the format as ISO8601 including timezone offset (the default format), as there will be no confusion in the future when looking at your dates.

If you were to approach a random vault (not yours) which had the date `2024-01-20 13:54:52` - what timezone is that in? You have no idea. So for best future proofing, I suggest leave it as the default which includes the timezone offset.
