### ISSUE TITLE
Option to not add the modified property automatically.

### ISSUE THREAD

**Issue by albertoloscerritos** [alangrainger/obsidian-frontmatter-modified-date#2]
Hi, I like you plugin a lot. It's really useful. there is just one problem. If the plugin is enabled, every time I update a note, the modified date gets automatically added to the frontmatter. And sometimes I don't want frontmatter in certain notes or I simply don't want to know the modified date for a specific note.

Solution: Add an option to only add the modified property if the modified value is already present in the frontmatter, that way we avoid the property being added automatically to the frontmatter. 

Thanks.

**Comment by alangrainger** [comment]
Added in 1.2.0:

https://github.com/alangrainger/obsidian-frontmatter-modified-date/releases/tag/1.2.0

**Comment by albertoloscerritos** [comment]
Thanks mate.
Plugins like yours really help the community. 👍
