### ISSUE TITLE
Feature Request: Date Link Support

### ISSUE THREAD

**Issue by bgk0018** [alangrainger/obsidian-frontmatter-modified-date#22]
Hey thanks for this plugin!

I wanted to see if it would be possible to add link support for dates. I prefer to have the date linked for create/update stamps instead of just flat text.

![image](https://github.com/alangrainger/obsidian-frontmatter-modified-date/assets/1944453/521b4c1a-3854-40f5-a3b7-0b3d1cf5dc24)

I found that if I gave the following moment.js format it created the shape I wanted:

`[[[]YYYY-MM-DD[]]]`

But unfortunately is considered an invalid date and so when doing a comparison, it just always appends every 10 seconds as `line 147` always returns `false`:

`now.isSame(previousEntryMoment, this.settings.appendMaximumFrequency)`

![image](https://github.com/alangrainger/obsidian-frontmatter-modified-date/assets/1944453/b2da9796-fd8b-4ab2-bfc0-d151430f3ebf)

The only way I could think to implement would be have a toggle for `dates-as-links` or something which would just concat onto the entries, and peel them off when having to re-parse.

Let me know if this is something you'd be open to adding, I may just do it myself locally.

**Comment by torrudev** [comment]
I found two workarrounds for this issue:

You can escape characters using `\` so using \[\[YYYY-MM-DD\]\] will work to create links

Also if you use obsidian date property type it shows a link icon for dates automatically

**Comment by alangrainger** [comment]
Hi @bgk0018 - just use the standard MomentJS date format as it says on the Settings page, and you can add the square brackets to show your dates as links:

Set your date format to:

```
[[[]YYYY-MM-DD[]]]
```

And the output will be a link.
