### ISSUE TITLE
It changes how lists look in the frontmatter

### ISSUE THREAD

**Issue by alexlyzhov** [alangrainger/obsidian-frontmatter-modified-date#24]
Before:
```
---
alias: [Academic research dashboard]
created: 2022-08-20
modified: 2024-01-21
---
```

After:
```
---
alias:
  - Academic research dashboard
created: 2022-08-20
modified: 2024-05-12
---
```

What I want:
```
---
alias: [Academic research dashboard]
created: 2022-08-20
modified: 2024-05-12
---
```

I want all elements of a list on the same line. I didn't find anything in the code that would change lists explicitly, so maybe this is just what Obsidian's processFrontMatter is doing? Is there a way to avoid this?

I've thought about fixing this with the Linter plugin. But if Linter lints on file close and then this plugin updates a list to be multiline in 10s, the file is saved with the undesirable formatting still.

**Comment by alangrainger** [comment]
Hi @alexlyzhov , this isn't to do with the plugin, this is how Obsidian itself formats frontmatter.

There are many threads on the forum about this, here's an official response from Obsidian team: 

https://forum.obsidian.md/t/api-processfrontmatter-removes-string-quotes-comments-types-formatting/65851/6
