### ISSUE TITLE
Modified date sorting in frontmatter

### ISSUE THREAD

**Issue by ricir** [alangrainger/obsidian-frontmatter-modified-date#27]
It seems that the appended date is added at the end of the array, so that in Live Preview and Reading mode the date shown is the first and not the last one. 
I do not know if this issue can be related to my chosen date-time format (YYYY-MM-DD HH:mm) or other issue not related to the plugin.

**Comment by alangrainger** [comment]
Added in 1.4.0

**Comment by ricir** [comment]
Please see new issue #28
