### ISSUE TITLE
Related to #27 - keeps adding new modification dates on top

### ISSUE THREAD

**Issue by ricir** [alangrainger/obsidian-frontmatter-modified-date#28]
When using the new inverse sort order, the plugin keeps adding new modification dates (on top as required).

```
modifiedDateTime:
  - 2024-08-12 16:51
  - 2024-08-12 16:51
  - 2024-08-12 16:50
  - 2024-08-12 16:50
  - 2024-08-11 17:23
append_modified_update: true
```

![image](https://github.com/user-attachments/assets/ee51b659-b344-40e4-849b-6bef2d48360c)

**Comment by alangrainger** [comment]
I can confirm things are working as expected at this end. 

Can you try two things:

1. Change from `day` to anything else, and then back again. Just to make sure it's correctly set in the `data.json`.
2. Post the string you're using for `Date format`.

**Comment by alangrainger** [comment]
I can see the issue - fixing now :+1:

**Comment by alangrainger** [comment]
Fixed in 1.4.1, please let me know

**Comment by ricir** [comment]
OK it's working now! 
I'll need to rearrange the old lists in reverse order.

**Comment by alangrainger** [comment]
Excellent!

For your existing notes, you can put this in a Templater template or CustomJS action, assign it to a hotkey, and then hit the hotkey every time you come across a note with them in the wrong order:

```js
<%*
app.fileManager.processFrontMatter(tp.config.target_file, frontmatter => {
  frontmatter.modifiedDateTime.reverse()
})
-%>
```

**Comment by ricir** [comment]
Perfect!

I ended up in a slightly modified version of your proposed template, in order to also deal with files with dates not sorted for any reason:

```typescript
<%*
app.fileManager.processFrontMatter(tp.config.target_file, frontmatter => {
  frontmatter.modifiedDateTime.sort()
})
app.fileManager.processFrontMatter(tp.config.target_file, frontmatter => {
  frontmatter.modifiedDateTime.reverse()
})
-%>

```
