### ISSUE TITLE
modify time is wrong

### ISSUE THREAD

**Issue by jsdwei** [alangrainger/obsidian-frontmatter-modified-date#29]
I just read a note, did not modify anything, but the modify time of the note has been updated. I even set default view for new tabs is reading view.

**Comment by alangrainger** [comment]
Try it in a Sandbox vault. You probably have another plugin modifying the file, like Linter.

**Comment by alangrainger** [comment]
Try it in a Sandbox vault. You probably have another plugin modifying the file, like Linter.

If you want to avoid updates when external processes modify your notes, turn on the setting to "Use typing events instead of Obsidian events".
