### ISSUE TITLE
"Use typing events" mode doesn't work on mobile

### ISSUE THREAD

**Issue by fivew4ys** [alangrainger/obsidian-frontmatter-modified-date#30]
When i first install it it works properly 
When you close and restart Obsidian. It doesn't work any more, only work for the first time. I've tried and wait with a brand new vault without other plugin to make sure

**Comment by alangrainger** [comment]
Interesting! Will have a look.

**Comment by alangrainger** [comment]
Are you using the "Use typing events instead of Obsidian events"? That one appears to be having issues on mobile. I will fix this.

If you're using the normal mode (which I recommend), I can't replicate the issue on mobile.

**Comment by fivew4ys** [comment]
Yeah that's resolve the problems at the moment 
Tysm 🙏🙏

**Comment by Offerel** [comment]
Are there any news on this topic? Disable the typing events, is not ideal, because this changes the file in a short time, multiple times. This in return triggers a sync of the file every time.

**Comment by alangrainger** [comment]
@Offerel have you increased the timeout time? 

![Screenshot_20241020-092927](https://github.com/user-attachments/assets/d72136f1-f0d5-47f8-a56a-d120523bdb24)

**Comment by Offerel** [comment]
Yes, its exactly 10 milliseconds. But also when i wait the standard 1 second (1000), it doesn't work

**Comment by alangrainger** [comment]
If you look closely at the screenshot you will see it's in seconds.

So for 1000 seconds you'll be waiting quite a while.

**Comment by alangrainger** [comment]
@Offerel in the screenshot you will see it's in seconds.

So for 1000 seconds you'll be waiting quite a while.

Try something like 60.

**Comment by Offerel** [comment]
I must be blind. Have it now on 7 and it works. It seems to work also with "typing events". Many thx.

**Comment by alangrainger** [comment]
Typing events on mobile are now working in 1.4.6

**Comment by alangrainger** [comment]
@fivew4ys Typing events on mobile are now working in 1.4.6
