### ISSUE TITLE
Using escaped characters in the time format causes constant updates

### ISSUE THREAD

**Issue by MMoMM-org** [alangrainger/obsidian-frontmatter-modified-date#31]
Hi, I tried to use the following format:

[[[]YYYY-MM-DD[]]]

This causes constant updates, even if with frequency updates of Day.

[[[]YYYY-MM-DD[]]] hh:mm 

has the same issues 😀

**Comment by alangrainger** [comment]
I can say it's a limitation of the Moment library - it's not able to parse square brackets within square brackets that I can see. Or at least I haven't been able to find any combination of escape characters that works. I will have to approach the problem a different way by handling the links outside Moment.

**Comment by alangrainger** [comment]
@MMoMM-org this should work now in 1.4.5 using this format:

```
[[[]YYYY-MM-DD[]]]
```

**Comment by MMoMM-org** [comment]
thanks!
