### ISSUE TITLE
Getting YYYY-MM-DD ddd to render as a date property

### ISSUE THREAD

**Issue by writtenfool** [alangrainger/obsidian-frontmatter-modified-date#34]
I use this format YYYY-MM-DD ddd in other Obsidian templates and such but I cannot get modified-date to render it as a link. To render this as a link, how do I tell modified-date to use list property to render this format YYYY-MM-DD ddd. What am I missing?

**Comment by alangrainger** [comment]
Like this: 

https://github.com/alangrainger/obsidian-frontmatter-modified-date?tab=readme-ov-file#date-format

`[[[]YYYY-MM-DD ddd[]]]`

**Comment by writtenfool** [comment]
I had been using your wonderful plugin for a while, so all the  properties were Date type. Soon as I changed to the type to list, all the notes now relfect the link format. Many thank yous!
