### ISSUE TITLE
Property added when it did not exist before

### ISSUE THREAD

**Issue by marjomol** [alangrainger/obsidian-frontmatter-modified-date#35]
Hi!

I've been using the plugin to automatically update the creation and modification dates of some of my notes for a while. Some notes have a creation date and last modification date property to update, but others only have one or none of them. That is why I used the option "only update existing fields". But recently it has started to fail and it creates the property field when it wasn't there before (for example, the creation date appears, and when I delete it, it appears again).

I'm using Obsidian 1.7.4 in an Ubuntu machine.

Thanks a lot.

**Comment by willasm** [comment]
I'm seeing this as well

If the frontmatter does NOT contain the `modified` OR both the `modified` and `created` fields, then nothing is created which is correct.
But if I DO have the `modified` field and do NOT have the `created` field, the the `created` field is created anyways.

I thought I had a fix, but it does not work correctly for all situations.

William.

**Comment by alangrainger** [comment]
Fixed in 1.4.7, thanks!
