### ISSUE TITLE
created frontmatter is never updated

### ISSUE THREAD

**Issue by willasm** [alangrainger/obsidian-frontmatter-modified-date#36]
I have a `created:` field in the frontmatter of my templates but the date is never filled in upon creation of a new note. I could just use `<% tp.date.now("yyyy-MM-DD HH:mm") %>` to have templater insert it for me but I would rather this plugin filled it in as all my templates are already setup this way. I was using the [update-time-on-edit-obsidian](https://github.com/beaussan/update-time-on-edit-obsidian) plugin which required the created field be blank. Unfortunately that plugin was not updating the modified date for me while editing a note and the author does not seem to be working on it any more. This plugin updates the modified date perfectly by the way! Just need to have the created field updated and it would be complete.

Thanks, William.

**Comment by willasm** [comment]
Found the problem. The created field option was never saved to `data.json` Easy to fix, just change `createdDateProperty: '',` to `createdDateProperty: 'created',` in your settings.ts file in the `export const DEFAULT_SETTINGS: FrontmatterModifiedSettings = {` block of code.

Works perfectly now, thanks, William.

**Comment by alangrainger** [comment]
The default setting is meant to be blank `''`. By default a created field will not be added, unless you fill in that field name yourself.

The text in the Settings box says "**Add** a created property name, and the plugin will also update it".
