### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MaxTheSpy** [alangrainger/obsidian-frontmatter-modified-date#37]
Ive been using this plugin for a while and I love it! Ive run into a few pain points though. Is there any way to add Created and Modified as the top 2 properties on documents automatically instead of having them be the bottom two for files already created?

I regularly transfer files out of my obsidian vault and into a remote vault on a hard drive running obsidian portable. The date created and modified refreshes, Is there a way to stop this from happening?

**Comment by alangrainger** [comment]
> Is there any way to add Created and Modified as the top 2 properties on documents automatically

You can use the Linter plugin for that:

https://github.com/platers/obsidian-linter

> I regularly transfer files out of my obsidian vault and into a remote vault on a hard drive running obsidian portable. The date created and modified refreshes, Is there a way to stop this from happening?

Yes - turn on the "Use typing events" option.

**Comment by MaxTheSpy** [comment]
Thank you! That seemed to have done the trick!

**Comment by MaxTheSpy** [comment]
Thank you! This seemed to have done the trick!
