### ISSUE TITLE
MomentJS "is a legacy project in maintenance mode"

### ISSUE THREAD

**Issue by xpe** [alangrainger/obsidian-frontmatter-modified-date#39]
It is nice to see this level of candor from a project:

https://momentjs.com/docs/?/displaying/format/

> ...
>
> Another common argument against using Moment in modern applications is its size. Moment doesn't work well with modern "tree shaking" algorithms, so it tends to increase the size of web application bundles. If one needs internationalization or time zone support, Moment can get quite large. Modern web browsers (and Node.js) expose internationalization and time zone support via the Intl object, codified as ECMA-402. Libraries like Luxon (and others) take advantage of this, reducing or removing the need to ship your own data files.
>
> Recently, Chrome Dev Tools started showing recommendations for replacing Moment for the size alone. We generally support this move.
>
> You may also want to read:
>
> - [You Probably Don't Need Moment.js Anymore](https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore)
> - [You don't (may not) need Moment.js](https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md)
> - [Why you shouldn't use Moment.js...](https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js)
> - [4 alternatives to moment.js for internationalizing dates](https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/)
>
> The Moment team has discussed these issues at length. We recognize that many existing projects may continue to use Moment, but we would like to discourage Moment from being used in new projects going forward. Instead, we would like to recommend alternatives that are excellent choices for use in modern applications today. We would also like to promote the Temporal addition to the JavaScript language, which is looking for feedback and contributors.
>
> We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.
>
> ...

**Comment by alangrainger** [comment]
Moment is imported from Obsidian core, it's not from this project. 

I would hope they're using DayJS as it's feature compatible and exports a `moment` object. 

Regardless, there's no action I can take within this plugin to affect the Obsidian devs decision.
