### ISSUE TITLE
[Bug] Modified date reappears after deleting the property.

### ISSUE THREAD

**Issue by albertoloscerritos** [alangrainger/obsidian-frontmatter-modified-date#4]
If I add a template to a note, that includes the modified date property. And the I decide I don't need properties in that note and decide to remove them all (by going into source mode and selecting and deleting everything). Or if I simply remove the modified date property by right clicking and removing, the property will reappear.
![bug_modified_2](https://github.com/alangrainger/obsidian-frontmatter-modified-date/assets/16707033/90f9b8d4-3505-4290-be95-eb5bb122b55d)
Thanks.

**Comment by alangrainger** [comment]
Yes, that would be the expected behaviour. By removing the property you are modifying the note, therefore the modified time will be updated.

You can turn on the option which will only update the property if it exists. That will cause it to not re-appear when you delete it.

**Comment by alangrainger** [comment]
Thanks, sorry I didn't see that in your original post.

Should be fixed in v1.2.1, can you test and let me know?

**Comment by albertoloscerritos** [comment]
Hi, I just test it for a couple of hours, and it seems to be working correctly. I will let you know if anything changes.
Thanks for your help.
