### ISSUE TITLE
Exclude single files from updating

### ISSUE THREAD

**Issue by ricir** [alangrainger/obsidian-frontmatter-modified-date#5]
I would like to be able to exclude a single file, for instance by adding a property in the YAML.

So far a workaround is to enclose all the files I do not want to update inside a specific folder ("No_update" for instance), however  the option could be very useful.

**Comment by alangrainger** [comment]
Done, this is available in v1.2.4

Add `exclude_modified_update` to your frontmatter and give it a value. You can set it to be a Checkbox property type if you like.
