### ISSUE TITLE
exclude_modified_update is not working

### ISSUE THREAD

**Issue by ricir** [alangrainger/obsidian-frontmatter-modified-date#6]
I added the field a gave it the value true (actually a checkbox) but the field specified in the options (`modifiedDateTime`) is still updating.
My fields:
```
exclude_modified_update: true
modifiedDateTime: 2023-09-14 16:26
```
I also tried to close Obsidian and reopen but this still happens.

**Comment by alangrainger** [comment]
Can you double-check you have  v1.2.4 of the plugin?

I just tried this in the sandbox vault and it works fine. I even copied and pasted the property name from your post just to make sure.

**Comment by ricir** [comment]
Alan

I think I should investigate my installation of Obsidian. There is
something very strange. I completely uninstalled the plugin and it kept
updating.

It seems like I have two Obsidians running in parallel, but I don't
know why and how to detect the situation.

There are also some issues with conflicting copies created every time the
field is updated (I am using Maestral with Dropbox).

I can give you more info tomorrow (now is about 9 PM CEST in Italy) if you
want.

Thanks for your help.

Riccardo

Il giorno gio 14 set 2023 alle ore 19:26 Alan Grainger <
***@***.***> ha scritto:

**Comment by ricir** [comment]
> Can you double-check you have v1.2.4 of the plugin?
> 
> I just tried this in the sandbox vault and it works as expected. I even copied and pasted the property name from your post just to make sure.
> 
> Here's a test vault showing it working - maybe you can test this on your machine and see if it still works correctly?
> 
> [Modified test vault.zip](https://github.com/alangrainger/obsidian-frontmatter-modified-date/files/12611713/Modified.test.vault.zip)

Yes, your vault is working correctly also with my installation of Obsidian. Therefore I think I need to investigate my vault (for instance possible conflicting  plugins).

**Comment by alangrainger** [comment]
Can you try uninstalling and reinstalling the plugin? I think that has a high chance of success.

If not, we can move onto other troubleshooting steps.

**Comment by ricir** [comment]
I did not reinstall, however now it is working on my vault too and conflicting copies stopped creating so far (maybe there was some problem on the Dropbox / Maestral side).
I think you can close this issue an I could open a new one if I find any other strange situation.
