### ISSUE TITLE
Modified date value update rate is slow

### ISSUE THREAD

**Issue by redactedscribe** [alangrainger/obsidian-frontmatter-modified-date#8]
This is exactly the plugin I was looking for; relying on the operating system for retrieving modified date metadata is flawed. Unfortunately, your plugin also seems to have some limitation, namely the rate at which it detects and updates the modified key.

There's probably a good reason behind not checking for a change every second and rewriting the key's value, but it's possible to edit a file and switch away or close Obsidian before the plugin updates the modified date (according to the developer of the obsidian-linter plugin, the latter doesn't have a good solution). This isn't so much of a problem of files you edited a moment ago, leading to inaccurate modified dates from seconds to minutes (which still irks me), but what if the file is one edited yesterday, or a week ago?

I saw in your commits you switched from `modify` to an `editor-change` event to avoid issues with Obsidian Sync (5d8abe3). Was the former more accurate at detecting and updating the modified date? If there's no other solution to improving the accuracy, maybe a way to opt-out of being Sync-compatible for more accurate modified dates? I see Obsidian saves the file / updates the modified date on the system within 2-3 seconds of any edit.

Thanks.

**Comment by alangrainger** [comment]
> There's probably a good reason behind not checking for a change every second and rewriting the key's value

I encourage you to read the readme, which explains all:

https://github.com/alangrainger/obsidian-frontmatter-modified-date#merging-changes-popup

> according to the developer of the obsidian-linter plugin, the latter doesn't have a good solution

Indeed.

> I saw in your commits you switched from modify to an editor-change event to avoid issues with Obsidian Sync (https://github.com/alangrainger/obsidian-frontmatter-modified-date/commit/5d8abe302e7a18fcd183b5a6902125f4efb0bbfc). Was the former more accurate at detecting and updating the modified date?

Worse. `modify` triggers on an external modification of the file, whereas `editor-change` is from internal editing.

**Comment by redactedscribe** [comment]
> I encourage you to read the readme, which explains all:
> 
> https://github.com/alangrainger/obsidian-frontmatter-modified-date#merging-changes-popup

It seems my testing was too hasty. Thank you. So by the sounds of it, as long as I don't quit Obsidian within 10 seconds of making an edit, the modified time should be updated in the background. And that's the only thing that which could cause the modified time to not be written? This is better than I thought.

**Comment by alangrainger** [comment]
> This is better than I thought.

But of course 👍
