### ISSUE TITLE
Exclude folders not working

### ISSUE THREAD

**Issue by redactedscribe** [alangrainger/obsidian-frontmatter-modified-date#9]
I have a folder named "Test" with a note inside of it. "Test" is also written in the "Exclude folders" option. Yet after 10 seconds, in this case, the front matter of the note is being deleted (probably because it contains Templater syntax and therefore not valid front matter).

- Why is the "Test" folder still being manipulated despite the exclusion? I've tried excluding "Test/" and "/Test" without luck. Also tried a differently named folder.
- If the folder _isn't_ excluded, the front matter shouldn't be being removed because this plugin believes it's invalid.
- I have the "Only update existing fields" option enabled, so I would've thought even without an exclusion this plugin wouldn't cause any modification/deletion due to the front matter being Templater syntax. **Edit:** This seem to work fine on non-excluded files with valid front matter.
- I am also using a custom front matter property key name.

Thanks.

**Comment by alangrainger** [comment]
Turns out that **reading** the frontmatter in Obsidian causes it to be reformatted. **Well that's a bit shit.**

Updated in 1.3.1 to use the cache instead.

**Comment by redactedscribe** [comment]
Thanks for the quick fix!
